#cloud-config
users:
  - name: web
    primary_group: web
    groups: wheel
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGx0YT3YlP68ezNQgXgr7df37kg9ZG705rJP1GlEg23O
package_update: true
packate_upgrade: true
packages:
  - nginx
  - nmap
